### PR TITLE
Adhere to new database

### PR DESCRIPTION
**Pull request by henrikauestad**

### CODE REVIEW

**Comment by henrikauestad** [comment]
The test only concers the classes in datahandler. The new process.Forecast class (did not see it before now, very cool) haven't been tested.

**Comment by olewu** [comment]
I haven't gotten around to fixing issue #36, which concerns the handling of the climatologies. Maybe we can review that part first.

**Comment by henrikauestad** [comment]
This contribution does not go into issue #36, but deals with the new filenames.

**Comment by olewu** [comment]
Oh, sorry about that, maybe I should have read the title of the request more carefully. Sure, let's merge this then @ssilje

**Pull request merged**
